[package]
name = "net-widget"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29.10"
humansize = "2.1.3"
chrono = "0.4.31"
tray-item = "0.10.0"
tray-icon = "0.20.0"

[build-dependencies]
embed-resource = "2.3"

